spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Uguimar-Platform/config-prod
          clone-on-start: true
          default-label: main
          timeout: 10
          search-paths: '{application}'
logging:
  level:
    root: WARN
    com.uguimar: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never